# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: troand
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shui-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  getMsgs:
    handler: functions/getMsgs/index.handler
    events:
      - httpApi:
          path: /
          method: GET

  postMsg:
    handler: functions/postMsg/index.handler
    events:
      - httpApi:
          path: /write
          method: POST

  getMsgById:
    handler: functions/getMsgById/index.handler
    events:
      - httpApi:
          path: /edit/{msgId}
          method: GET

  patchMsg:
    handler: functions/patchMsg/index.handler
    events:
      - httpApi:
          path: /edit/{msgId}
          method: PATCH

resources:
  Resources:
    shuiMsg:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shuiMsg
        AttributeDefinitions:
          - AttributeName: msgId
            AttributeType: S
        KeySchema:
          - AttributeName: msgId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
